### ISSUE TITLE
php artisan apikey:generate app1

### ISSUE THREAD

**Issue by atarekk** [ejarnutowski/laravel-api-key#1]
Invalid name.  Must be a lowercase alphabetic characters and hyphens less than 255 characters long.

**Comment by ejarnutowski** [comment]
What exactly is the issue?

**Comment by atarekk** [comment]
when write this command php artisan apikey:generate app1 i get this error : Invalid name. Must be a lowercase alphabetic characters and hyphens less than 255 characters long.

**Comment by ejarnutowski** [comment]
That’s not a bug.  That’s how it’s designed and documented.  Please submit a pull request if you’d like a change.

**Comment by ejarnutowski** [comment]
Apologies... I see what you are talking about.  I’ll make an update.

**Comment by atarekk** [comment]
welcome waiting for your update :+1:

**Comment by ejarnutowski** [comment]
This has been fixed
