### ISSUE TITLE
apikey:generate throws error

### ISSUE THREAD

**Issue by baradhili** [ejarnutowski/laravel-api-key#11]
running laravel 6.4.0, laravel-api-key 1.0.3
when calling php artisan `apikey:generate app` I get

`
   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Ejarnutowski\LaravelApiKey\Models\str_random()

  at /home/vagrant/code/vendor/ejarnutowski/laravel-api-key/src/Models/ApiKey.php:79
    75|      */
    76|     public static function generate()
    77|     {
    78|         do {
  > 79|             $key = str_random(64);
    80|         } while (self::keyExists($key));
    81| 
    82|         return $key;
    83|     }

  Exception trace:

  1   Ejarnutowski\LaravelApiKey\Models\ApiKey::generate()
      /home/vagrant/code/vendor/ejarnutowski/laravel-api-key/src/Console/Commands/GenerateApiKey.php:46

  2   Ejarnutowski\LaravelApiKey\Console\Commands\GenerateApiKey::handle()
      /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
`

I also noticed it complains if I use the readme example of app1

**Comment by swapnilsarwe** [comment]
The package has been updated with the fix 2 months ago. But I guess its not been tagged as a new version and hence you are still having the old code under the version `1.0.3`.

**Comment by swapnilsarwe** [comment]
Till the time the package maintainer does not release the new version, you can use `dev-master` as a version in `composer.json`.
```php
"require": {
    ...
    "ejarnutowski/laravel-api-key": "dev-master",
    ...
},
```

**Comment by ejarnutowski** [comment]
@baradhili, @swapnilsarwe,

Apologies - as @swapnilsarwe stated, the pull request was merged but not tagged.  Please update your composer with 1.0.4.  It should be all set now.

**Comment by baradhili** [comment]
Thanks!
