### ISSUE TITLE
Disable auth.apikey middleware for sessions

### ISSUE THREAD

**Issue by bratelefant** [ejarnutowski/laravel-api-key#12]
Is it possible to sort of disable ``->middleware('auth.apikey')`` on api routes if the api calls are consumed during a web session on the frontend? Not actually an issue rather a feature request.
thx in advance

**Comment by ejarnutowski** [comment]
Sounds like you should use something other than this library, or build additional API endpoints to feed data to your front end, which are authenticated by another method, such as a token.  This library is specifically for external 3rd party access.

**Comment by bratelefant** [comment]
I guess not. I want to be able to give API keys to 3rd parties. At the same time I want to consume my own API on the frontend via axios calls, but I don't want to include an API key in those requests as this is client side and, hence, public.

**Comment by ejarnutowski** [comment]
Sounds like you want to use 2 sets of API’s: one set for your front end using session/token middleware, and one set for your 3rd party access using the laravel-api-key middleware.
