### ISSUE TITLE
Error in the lumen

### ISSUE THREAD

**Issue by majidazizian** [ejarnutowski/laravel-api-key#13]
I get this error in Luman when I run the `php artisan vendor: publish` command.

`In BoundMethod.php line 165:`                                             
`Class Illuminate \ Routing \ Router does not exist`

**Comment by EminDemiri** [comment]
Hi, I had the same problem.

I solved it by adding the dependency in the composer:
`"illuminate/routing": "^5.5|^6|^7"`

This is because lumen uses different namespaces for routing

**Comment by majidazizian** [comment]
> Hi, I had the same problem.
> I solved it by adding the dependency in the composer:
> `"illuminate / routing": "^ 5.5 | ^ 6 | ^ 7"`
> 
> This is because lumen uses different namespaces for routing

Unfortunately, it didn't help me

**Comment by ejarnutowski** [comment]
@majidazizian did you find a solution?  This library wasn't developed with Lumen in mind, but if it could work with Lumen, great.
