### ISSUE TITLE
Custom exception handler

### ISSUE THREAD

**Issue by iraldoad** [ejarnutowski/laravel-api-key#15]
Is it possible to customize the JSON response in case of error for not sending the X-Authorization header?

**Comment by iraldoad** [comment]
You can throw an UnauthorizedHttpException or similar here?

https://github.com/ejarnutowski/laravel-api-key/blob/81ac0a4732d1a6b515f2d8ea6f4419aed7451393/src/Http/Middleware/AuthorizeApiKey.php#L31

**Comment by iraldoad** [comment]
You can change this:
```php
return response([
            'errors' => [[
                'message' => 'Unauthorized'
            ]]
        ], 401);
```
for this or similar:
```php
throw new UnauthorizedHttpException(self::AUTH_HEADER);
```

**Comment by ejarnutowski** [comment]
This is intended.  See my comment in https://github.com/ejarnutowski/laravel-api-key/pull/17 about supporting optional custom responses.
