### ISSUE TITLE
Custom Database Schema

### ISSUE THREAD

**Issue by Fr4gger** [ejarnutowski/laravel-api-key#3]
Hi,

I just started used this library and I found it very interesting and useful. I just wanted to ask if there is a way I can set a database schema for the library to use instead of the default one. That'd be great.

Thanks in advance for your help.

**Comment by ejarnutowski** [comment]
@Fr4gger, please propose an example.  Thanks.

**Comment by Fr4gger** [comment]
@ejarnutowski I already solved the problem. It was my misunderstanding of the library functionality. Thanks anyway.

**Comment by ejarnutowski** [comment]
Sounds good.
