### ISSUE TITLE
Get Authentificate User Data

### ISSUE THREAD

**Issue by luisferparra** [ejarnutowski/laravel-api-key#4]
Hi

I'm using your package for accessing an api. It works perfectly but I've got the problem that once the user is logged or accessed correctly, I cannot get User information such as id or user name.

neither Auth::user() (returns null), $request->user() or whatever works correctly. At the controller I.e. the Auth::check returns false.

How can I get information about user logged??

thanks

**Comment by ejarnutowski** [comment]
@luisferparra , can you confirm that your issue is with this library specifically?
